### PR TITLE
Notify user on successful builds

### PR DESCRIPTION
**Pull request by bennycwong**
Adding this new feature will allow developers to get a growl notification on build success so they don't have to switch back to the terminal to confirm a build is complete.

### CODE REVIEW

**Comment by briangonzalez** [comment]
+1

**Comment by pdud** [comment]
@bennycwong looks like a great feature! Thanks!

Let’s make this functionality opt-in, defaulting to no notification for successful builds.

This weekend, I've added https://github.com/pdud/ember-cli-build-notifications/pull/10 to support a config file at `config/build-notifications.js`. With the config file we could make it possible to enable a notification on a successful build like this.

```javascript
module.exports = {
  postBuild: {
    notify: true
  }
};
```

Long term it could be used to add sound, change the icons or change messages.

This will require some updates to the work you did. Are you interested in making those changes? If you prefer I could make them.

**Comment by vlascik** [comment]
Will this get merged anytime soon? Build success notification would be most helpful.

**Comment by bennycwong** [comment]
Closed... see [#12](https://github.com/pdud/ember-cli-build-notifications/pull/12) for the updated code.

**Comment by pdud** [comment]
Thanks to @bennycwong build success notifications are now possible! (They are off by default)

https://github.com/pdud/ember-cli-build-notifications/blob/master/tests/fixtures/config/build-notifications.js

That file will need to exist in `<repo_name>/config/build-notifications.js`. You can then customize what notifications you want.

Upgrading to v0.1.0 will add this functionality.

**Comment by vlascik** [comment]
thanks, it works well, there is a typo in README that tripped me up though :).
`To override defaults, add the following to the config file {app}/config/build-notification.js:`
should be
`To override defaults, add the following to the config file {app}/config/build-notifications.js:`

**Comment by pdud** [comment]
Ah you're right! Are you interested in making a pull request with the fix? If you prefer I could. 

Thanks for letting us know!

**Pull request closed without merging**
