### PR TITLE
Notify user on successful builds: off by default. 

### PR DESCRIPTION
**Pull request by bennycwong**
1. Added a feature to notify user when build succeeds, with build time information
2. The build succeeded feature is off by default. It can be turned on in config/build-notifications.js
3. Added unit test for the notification.

### CODE REVIEW

**Comment by bennycwong** [comment]
Suggestion: I could also rename the [notify method](https://github.com/pdud/ember-cli-build-notifications/blob/master/lib/notifier.js#L8) to buildFailed

**Comment by pdud** [comment]
This looks awesome!! Thank you very much

**Comment by pdud** [comment]
I like your suggestion as well. What are your thoughts on naming it buildError to match the wording ember-cli uses?

**Comment by bennycwong** [comment]
@pdud see #13

**Pull request merged**
