### PR TITLE
Use node-notifier

### PR DESCRIPTION
**Pull request by tchak**
By using node-notifier this addon will work on linux and windows

### CODE REVIEW

**Comment by pdud** [comment]
Great PR! Thank you! I was also looking to use node-notifier over the weekend after I saw issue #1.

Can you add in the icon and remove the tests?

Thanks again!

**Comment by manuelmitasch** [comment]
:+1:

**Comment by salzhrani** [comment]
Please add notification sound as an option

**Comment by tchak** [comment]
@pdud sorry for not reacting earlier... Thank's for taking it over :)

**Pull request merged**
